# Generated by Django 3.1.5 on 2021-02-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoices',
            name='i',
        ),
        migrations.AddField(
            model_name='userchoices',
            name='choices',
            field=models.ManyToManyField(to='Test.Questions'),
        ),
    ]
