# Generated by Django 3.1.5 on 2021-02-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20210207_0809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChoices',
        ),
    ]
