# Generated by Django 3.1.5 on 2021-02-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_delete_userchoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
