# Generated by Django 3.1.5 on 2021-02-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20210207_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
    ]
