# Generated by Django 3.1.5 on 2021-02-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_auto_20210207_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='personality_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
