# Generated by Django 3.1.5 on 2021-02-09 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_auto_20210209_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('url_key', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
