# Generated by Django 3.1.5 on 2021-02-09 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_auto_20210209_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='url_key',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
