# Generated by Django 3.1.5 on 2021-02-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0012_auto_20210209_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TestRecord',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='username',
            name='personality_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='question_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.question'),
        ),
        migrations.AddField(
            model_name='userchoices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.username'),
        ),
    ]
