# Generated by Django 3.1.5 on 2021-02-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0013_auto_20210209_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChoices',
            new_name='UserChoice',
        ),
    ]
