# Generated by Django 3.1.5 on 2021-02-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_auto_20210214_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='url_key',
            new_name='url_keyy',
        ),
    ]
