# Generated by Django 3.1.5 on 2021-02-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0016_auto_20210214_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='url_keyy',
            new_name='url_key',
        ),
    ]
