# Generated by Django 3.1.5 on 2021-02-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0017_auto_20210214_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='url_key',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
