# Generated by Django 3.1.5 on 2021-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0023_auto_20210215_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='agreeable_score',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='username',
            name='conscientious_score',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='username',
            name='extroversion_score',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='username',
            name='neurotic_score',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='username',
            name='open_score',
            field=models.IntegerField(default=3),
        ),
    ]
