# Generated by Django 3.1.5 on 2021-02-18 04:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0025_auto_20210217_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('url_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('personality_type', models.IntegerField(blank=True, null=True)),
                ('extroversion_score', models.IntegerField(default=3)),
                ('neurotic_score', models.IntegerField(default=3)),
                ('agreeable_score', models.IntegerField(default=3)),
                ('conscientious_score', models.IntegerField(default=3)),
                ('open_score', models.IntegerField(default=3)),
            ],
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.userdata'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.userdata'),
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
