# Generated by Django 3.1.5 on 2021-02-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0026_auto_20210218_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='agreeable_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='conscientious_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='extroversion_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='neurotic_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='open_score',
            field=models.IntegerField(blank=True),
        ),
    ]
