# Generated by Django 3.1.5 on 2021-02-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0027_auto_20210218_0507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChoice',
        ),
    ]
